<?php /*

   PWNC Web Platform
   Copyright © 2026–present Patrick Heyer
   https://pwnc.it

   This software is subject to the included license.
   Please see /LICENSE.md for full details.

*/

namespace cms;

//==================================================================================================
//   COMMON LIBRARY
//==================================================================================================

require("common/codec.inc");
require("common/comm.inc");
require("common/date.inc");
require("common/file.inc");
require("common/hash.inc");
require("common/ice.inc");
require("common/image.inc");
require("common/language.inc");
require("common/math.inc");
require("common/misc.inc");
require("common/mysql.inc");
require("common/snippet.inc");
require("common/string.inc");
require("common/text.inc");
require("common/url.inc");